/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Debug_CSR101x_A05/app_gatt_db.db_
 */

#include "depend_Debug_CSR101x_A05/app_gatt_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 1800 */
    0x0002, 0x0018,
    /* 0002: Characteristic Declaration 2a00 */
    0x3005, 0x0203, 0x0000, 0x2a00,
    /* 0003: . */
    0xd401, 0x0000,
    /* 0004: Characteristic Declaration 2a01 */
    0x3005, 0x0205, 0x0001, 0x2a00,
    /* 0005: .. */
    0xd002, 0x0000,
    /* 0006: Characteristic Declaration 2a04 */
    0x3005, 0x0207, 0x0004, 0x2a00,
    /* 0007: @.P..... */
    0xd008, 0x4000, 0x5000, 0x0400, 0xc800,
    /* 0008: Primary Service 1801 */
    0x0002, 0x0118,
    /* 0009: Primary Service 5ab20001-b355-4d8a-96ef-2963812dd0b8 */
    0x0010, 0xb8d0, 0x2d81, 0x6329, 0xef96, 0x8a4d, 0x55b3, 0x0100, 0xb25a,
    /* 000a: Characteristic Declaration 5ab20002-b355-4d8a-96ef-2963812dd0b8 */
    0x3013, 0x020b, 0x00b8, 0xd02d, 0x8163, 0x29ef, 0x968a, 0x4d55, 0xb302, 0x00b2, 0x5a00,
    /* 000b:  */
    0xc400,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
